name: flutter_multi_modular_clean_architecture
packages:
  - core/**
  - features/**

command:
  bootstrap:
    environment:
      sdk: ^3.6.1
      flutter: ">=1.17.0"
      
    dependencies:
      dio: ^5.8.0+1
    
    dev_dependencies:
      flutter_lints: ^5.0.0